-- Kitchen Maintenance (Kitchen app) — Chef Andrea through Tell us, 25 Sep 2026 (inbox fe2b2456):
-- "Every fault, breakdown or maintenance issue reported in the kitchen must generate a job card",
-- plus a calendar of recurring maintenance (grease trap, hood & extraction, servicing, preventive).
-- Built to the mock-up Francesco approved on 25 Sep 2026 and his rules:
--   · every signature is a STAFF CODE (the employee ID, typed again at the moment of signing)
--   · the technician is Andrea Falcone for testing, until the new technician is hired; that is a
--     row in maint_people, not code
--   · the chef-in-charge check is Danilo or Antonio only (maint_people role 'chef'); a card is not
--     closed until one of them signs, and it cannot be the same person who signed as technician
--   · a new card alerts the technician by email and in the app (the Home badge); a completed card
--     emails the chefs for their check
--
-- Every table is RLS-on with NO policy; everything goes through the security-definer maint_*
-- functions. Sign-in is the employee ID, like Learning and Training (learn_who).
-- Emails are QUEUED by the database (maint_mail) and sent by the edge function maint-notify,
-- which the database calls itself through pg_net. The app never calls it, so the function
-- can only ever send a mail the database has already queued, to the people the database chose.
-- A card reported by a test person (staff name starting "zz") or for equipment starting "zz" is
-- a TEST card: its mails go to Francesco only, with [TEST] in the subject.
--
-- Kitchen database: zrpglswalgjbtghudmhu

create table if not exists maint_people (
  staff_id uuid not null,
  role text not null check (role in ('technician','chef')),
  email text not null,
  active boolean not null default true,
  primary key (staff_id, role)
);

create table if not exists maint_cards (
  id uuid primary key default gen_random_uuid(),
  card_no bigint generated by default as identity unique,
  is_test boolean not null default false,
  source text not null default 'report' check (source in ('report','calendar')),
  task_id uuid,
  reported_by_id uuid, reported_by text not null, reported_at timestamptz not null default now(),
  location text not null, equipment text not null, problem text not null,
  media jsonb not null default '[]'::jsonb,
  status text not null default 'new' check (status in ('new','acknowledged','in_progress','on_hold','completed')),
  read_at timestamptz, read_by text,
  tech_id uuid, tech_name text,
  started_at timestamptz, hold_at timestamptz, hold_reason text,
  diagnosis text, cause text, solution text, est_cost numeric(12,2), est_time text, parts text, notes text,
  assessed_at timestamptz, assessed_by text,
  work_done text, final_cost numeric(12,2), completed_at timestamptz,
  tech_signed_id uuid, tech_signed_by text,
  checked_at timestamptz, checked_id uuid, checked_by text,
  sent_back_at timestamptz, sent_back_by text, sent_back_note text,
  updated_at timestamptz not null default now()
);
create index if not exists maint_cards_open on maint_cards(checked_at, status);
create index if not exists maint_cards_task on maint_cards(task_id);

create table if not exists maint_tasks (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  kind text not null default 'other' check (kind in ('grease','hood','service','preventive','other')),
  location text not null default '', equipment text not null default '',
  every_n int not null check (every_n between 1 and 366),
  every_unit text not null check (every_unit in ('day','week','month')),
  next_due date not null,
  by_who text not null default '',
  notes text not null default '',
  active boolean not null default true,
  created_by text not null, created_at timestamptz not null default now()
);

create table if not exists maint_task_log (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references maint_tasks(id) on delete cascade,
  done_on date not null, done_at timestamptz not null default now(),
  done_by text not null, note text, card_id uuid
);
create index if not exists maint_task_log_task on maint_task_log(task_id, done_on desc);

create table if not exists maint_mail (
  id bigint generated by default as identity primary key,
  card_id uuid not null references maint_cards(id) on delete cascade,
  kind text not null check (kind in ('new','check')),
  to_list text[] not null,
  is_test boolean not null default false,
  status text not null default 'queued' check (status in ('queued','sending','sent','failed')),
  tries int not null default 0,
  resend_id text, error text,
  created_at timestamptz not null default now(), sent_at timestamptz
);
create index if not exists maint_mail_status on maint_mail(status, created_at);

alter table maint_people   enable row level security;
alter table maint_cards    enable row level security;
alter table maint_tasks    enable row level security;
alter table maint_task_log enable row level security;
alter table maint_mail     enable row level security;
revoke all on maint_people, maint_cards, maint_tasks, maint_task_log, maint_mail from anon, authenticated;

-- ── who is who ────────────────────────────────────────────────────────────
create or replace function maint_has(p_staff uuid, p_role text) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from maint_people where staff_id = p_staff and role = p_role and active)
$$;
create or replace function maint_today() returns date
language sql stable as $$ select (now() at time zone 'Asia/Dubai')::date $$;

create or replace function maint_me(p_emp text) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s staff;
begin
  s := learn_who(p_emp);
  return jsonb_build_object('staff_id', s.id, 'name', s.name, 'designation', s.designation,
    'tech', maint_has(s.id,'technician'), 'chef', maint_has(s.id,'chef'),
    'techs', (select coalesce(jsonb_agg(st.name order by st.name), '[]'::jsonb) from maint_people mp join staff st on st.id = mp.staff_id where mp.role='technician' and mp.active),
    'chefs', (select coalesce(jsonb_agg(st.name order by st.name), '[]'::jsonb) from maint_people mp join staff st on st.id = mp.staff_id where mp.role='chef' and mp.active));
end $$;

-- What the report form offers as it is typed: the kitchen sections, the usual areas, and every
-- place and piece of equipment used on a card or a calendar job before.
create or replace function maint_places(p_emp text) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s staff;
begin
  s := learn_who(p_emp);
  return jsonb_build_object(
    'locations', (select coalesce(jsonb_agg(v order by v), '[]'::jsonb) from (
       select distinct v from (
         select label v from stations where active
         union select unnest(array['Hot kitchen','Cold room','Walk-in chiller','Walk-in freezer','Pastry','Pass','Dishwash area','Dry store','Bar','Staff area'])
         union select location from maint_cards where not is_test
         union select location from maint_tasks where active and location <> '') x where coalesce(v,'') <> '') y),
    'equipment', (select coalesce(jsonb_agg(v order by v), '[]'::jsonb) from (
       select distinct v from (
         select equipment v from maint_cards where not is_test
         union select equipment from maint_tasks where active and equipment <> '') x where coalesce(v,'') <> '') y));
end $$;

-- ── mail queue ────────────────────────────────────────────────────────────
-- The anon key is the public one already in every Kitchen page; the function checks nothing but
-- that the row it is handed is still queued.
create or replace function maint_kick(p_mail bigint) returns void
language plpgsql security definer set search_path to 'public' as $$
begin
  perform net.http_post(
    url := 'https://zrpglswalgjbtghudmhu.supabase.co/functions/v1/maint-notify',
    headers := jsonb_build_object('Content-Type','application/json',
      'Authorization','Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpycGdsc3dhbGdqYnRnaHVkbWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5MTIyMjQsImV4cCI6MjA5NjQ4ODIyNH0.pfABN-so4xINK7nHxXUlVeTO4g0h0l6ILHVwpoKrbds'),
    body := jsonb_build_object('mail', p_mail));
end $$;

create or replace function maint_queue(p_card uuid, p_kind text) returns void
language plpgsql security definer set search_path to 'public' as $$
declare c maint_cards; v_to text[]; v_id bigint;
begin
  select * into c from maint_cards where id = p_card;
  if c.is_test then v_to := array['fguarracino@robertos.ae'];
  else
    select array_agg(distinct lower(email)) into v_to from maint_people
     where active and role = case when p_kind = 'new' then 'technician' else 'chef' end;
  end if;
  if v_to is null or cardinality(v_to) = 0 then return; end if;
  insert into maint_mail(card_id, kind, to_list, is_test) values (p_card, p_kind, v_to, c.is_test) returning id into v_id;
  perform maint_kick(v_id);
end $$;

-- ── cards ─────────────────────────────────────────────────────────────────
create or replace function maint_card_row(c maint_cards) returns jsonb
language sql stable as $$ select to_jsonb(c) - 'tech_signed_id' - 'checked_id' - 'reported_by_id' $$;

create or replace function maint_list(p_emp text) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s staff;
begin
  s := learn_who(p_emp);
  return jsonb_build_object(
    'cards', coalesce((select jsonb_agg(jsonb_build_object('id', c.id, 'card_no', c.card_no, 'status', c.status, 'source', c.source,
        'location', c.location, 'equipment', c.equipment, 'problem', left(c.problem, 140), 'reported_by', c.reported_by, 'reported_at', c.reported_at,
        'tech_name', c.tech_name, 'hold_reason', c.hold_reason, 'completed_at', c.completed_at, 'checked_at', c.checked_at, 'checked_by', c.checked_by,
        'sent_back_at', c.sent_back_at, 'media', jsonb_array_length(c.media), 'is_test', c.is_test,
        'photos', (select count(*) from jsonb_array_elements(c.media) m where m->>'kind' = 'photo'),
        'videos', (select count(*) from jsonb_array_elements(c.media) m where m->>'kind' = 'video'),
        'due', (select t.next_due from maint_tasks t where t.id = c.task_id))
      order by c.reported_at desc) from maint_cards c
      where c.checked_at is null or c.checked_at > now() - interval '120 days'), '[]'::jsonb));
end $$;

create or replace function maint_get(p_emp text, p_id uuid) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s staff; c maint_cards;
begin
  s := learn_who(p_emp);
  select * into c from maint_cards where id = p_id;
  if c.id is null then raise exception 'no_card' using errcode = 'P0001'; end if;
  return jsonb_build_object('card', maint_card_row(c),
    'me', jsonb_build_object('tech', maint_has(s.id,'technician'), 'chef', maint_has(s.id,'chef'),
                             'signed_as_tech', c.tech_signed_id = s.id));
end $$;

-- Opening a card as the technician is the moment it was READ: stamped once, and a New card
-- becomes Acknowledged with that technician on it.
create or replace function maint_read(p_emp text, p_id uuid) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s staff; c maint_cards;
begin
  s := learn_who(p_emp);
  if not maint_has(s.id,'technician') then return null; end if;
  update maint_cards set read_at = now(), read_by = s.name,
         tech_id = coalesce(tech_id, s.id), tech_name = coalesce(tech_name, s.name),
         status = case when status = 'new' then 'acknowledged' else status end, updated_at = now()
   where id = p_id and read_at is null returning * into c;
  return case when c.id is null then null else maint_card_row(c) end;
end $$;

create or replace function maint_report(p_emp text, p_location text, p_equipment text, p_problem text, p_media jsonb) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s staff; c maint_cards; m jsonb; v_media jsonb := '[]'::jsonb;
begin
  s := learn_who(p_emp);
  if length(trim(coalesce(p_location,''))) < 2 then raise exception 'no_location' using errcode = 'P0001'; end if;
  if length(trim(coalesce(p_equipment,''))) < 2 then raise exception 'no_equipment' using errcode = 'P0001'; end if;
  if length(trim(coalesce(p_problem,''))) < 3 then raise exception 'no_problem' using errcode = 'P0001'; end if;
  if jsonb_typeof(coalesce(p_media,'[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_media,'[]'::jsonb)) > 8 then raise exception 'bad_media' using errcode = 'P0001'; end if;
  for m in select * from jsonb_array_elements(coalesce(p_media,'[]'::jsonb)) loop
    if coalesce(m->>'path','') !~ '^c/[0-9a-f-]{36}/[A-Za-z0-9._-]+$'
       or not exists(select 1 from storage.objects o where o.bucket_id = 'maint-media' and o.name = m->>'path') then
      raise exception 'bad_media' using errcode = 'P0001'; end if;
    v_media := v_media || jsonb_build_array(jsonb_build_object('path', m->>'path',
      'kind', case when m->>'kind' = 'video' then 'video' else 'photo' end, 'size', coalesce((m->>'size')::bigint, 0)));
  end loop;
  insert into maint_cards(is_test, reported_by_id, reported_by, location, equipment, problem, media)
  values (s.name ~* '^zz' or trim(p_equipment) ~* '^zz', s.id, s.name, left(trim(p_location),120), left(trim(p_equipment),120), left(trim(p_problem),2000), v_media)
  returning * into c;
  perform maint_queue(c.id, 'new');
  return jsonb_build_object('id', c.id, 'card_no', c.card_no);
end $$;

create or replace function maint_amount(p text) returns numeric
language plpgsql immutable as $$
begin
  if p is null or trim(p) = '' then return null; end if;
  if trim(p) !~ '^\d{1,7}(\.\d{1,2})?$' then raise exception 'bad_amount' using errcode = 'P0001'; end if;
  return trim(p)::numeric;
end $$;

create or replace function maint_step(p_emp text, p_id uuid, p_op text, p_args jsonb) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s staff; c maint_cards; a jsonb := coalesce(p_args,'{}'::jsonb); v_tech boolean; v_chef boolean;
begin
  s := learn_who(p_emp);
  v_tech := maint_has(s.id,'technician'); v_chef := maint_has(s.id,'chef');
  select * into c from maint_cards where id = p_id for update;
  if c.id is null then raise exception 'no_card' using errcode = 'P0001'; end if;
  if c.checked_at is not null then raise exception 'closed' using errcode = 'P0001'; end if;

  if p_op in ('start','hold','resume','assess','complete') then
    if not v_tech then raise exception 'not_tech' using errcode = 'P0001'; end if;
    if c.status = 'completed' then raise exception 'completed' using errcode = 'P0001'; end if;
    -- anything the technician does is also the moment it was read
    update maint_cards set read_at = coalesce(read_at, now()), read_by = coalesce(read_by, s.name),
           tech_id = coalesce(tech_id, s.id), tech_name = coalesce(tech_name, s.name) where id = p_id;
  end if;

  if p_op = 'start' then
    update maint_cards set status = 'in_progress', started_at = coalesce(started_at, now()), hold_reason = null, updated_at = now() where id = p_id;
  elsif p_op = 'hold' then
    update maint_cards set status = 'on_hold', hold_at = now(), hold_reason = nullif(left(trim(coalesce(a->>'reason','')),200),''), updated_at = now() where id = p_id;
  elsif p_op = 'resume' then
    if c.status <> 'on_hold' then raise exception 'not_on_hold' using errcode = 'P0001'; end if;
    update maint_cards set status = 'in_progress', started_at = coalesce(started_at, now()), hold_reason = null, updated_at = now() where id = p_id;
  elsif p_op = 'assess' then
    update maint_cards set
      diagnosis = nullif(left(trim(coalesce(a->>'diagnosis','')),2000),''),
      cause     = nullif(left(trim(coalesce(a->>'cause','')),1000),''),
      solution  = nullif(left(trim(coalesce(a->>'solution','')),1000),''),
      est_cost  = maint_amount(a->>'est_cost'),
      est_time  = nullif(left(trim(coalesce(a->>'est_time','')),120),''),
      parts     = nullif(left(trim(coalesce(a->>'parts','')),1000),''),
      notes     = nullif(left(trim(coalesce(a->>'notes','')),2000),''),
      assessed_at = now(), assessed_by = s.name, updated_at = now()
    where id = p_id;
  elsif p_op = 'complete' then
    if trim(coalesce(a->>'code','')) <> trim(s.emp_id) then raise exception 'bad_code' using errcode = 'P0001'; end if;
    if length(trim(coalesce(a->>'work_done',''))) < 3 then raise exception 'no_work' using errcode = 'P0001'; end if;
    if maint_amount(a->>'final_cost') is null then raise exception 'no_cost' using errcode = 'P0001'; end if;
    update maint_cards set status = 'completed', work_done = left(trim(a->>'work_done'),2000), final_cost = maint_amount(a->>'final_cost'),
           completed_at = now(), tech_signed_id = s.id, tech_signed_by = s.name, hold_reason = null, updated_at = now()
     where id = p_id;
    perform maint_queue(p_id, 'check');
  elsif p_op = 'check' then
    if not v_chef then raise exception 'not_chef' using errcode = 'P0001'; end if;
    if c.status <> 'completed' then raise exception 'not_completed' using errcode = 'P0001'; end if;
    if trim(coalesce(a->>'code','')) <> trim(s.emp_id) then raise exception 'bad_code' using errcode = 'P0001'; end if;
    if c.tech_signed_id = s.id then raise exception 'same_person' using errcode = 'P0001'; end if;
    update maint_cards set checked_at = now(), checked_id = s.id, checked_by = s.name, updated_at = now() where id = p_id;
    -- a card the calendar opened closes its calendar job too, and the next date rolls on
    if c.task_id is not null then perform maint_task_did(c.task_id, (c.completed_at at time zone 'Asia/Dubai')::date, c.tech_signed_by, 'Job card JC-' || lpad(c.card_no::text, 4, '0'), c.id); end if;
  elsif p_op = 'send_back' then
    if not v_chef then raise exception 'not_chef' using errcode = 'P0001'; end if;
    if c.status <> 'completed' then raise exception 'not_completed' using errcode = 'P0001'; end if;
    if length(trim(coalesce(a->>'note',''))) < 3 then raise exception 'no_note' using errcode = 'P0001'; end if;
    update maint_cards set status = 'in_progress', completed_at = null, tech_signed_id = null, tech_signed_by = null,
           sent_back_at = now(), sent_back_by = s.name, sent_back_note = left(trim(a->>'note'),500), updated_at = now() where id = p_id;
  else
    raise exception 'bad_op' using errcode = 'P0001';
  end if;
  select * into c from maint_cards where id = p_id;
  return maint_card_row(c);
end $$;

-- For the Home tile: no sign-in, counts only.
create or replace function maint_summary() returns jsonb
language sql stable security definer set search_path to 'public' as $$
  select jsonb_build_object(
    'open',    (select count(*) from maint_cards where checked_at is null and not is_test),
    'new',     (select count(*) from maint_cards where status = 'new' and not is_test),
    'to_check',(select count(*) from maint_cards where status = 'completed' and checked_at is null and not is_test),
    'overdue', (select count(*) from maint_tasks where active and next_due < maint_today()))
$$;

-- ── calendar ──────────────────────────────────────────────────────────────
create or replace function maint_step_date(d date, n int, u text) returns date
language sql immutable as $$
  select (d + case u when 'day' then make_interval(days => n) when 'week' then make_interval(weeks => n) else make_interval(months => n) end)::date
$$;

create or replace function maint_task_did(p_task uuid, p_on date, p_by text, p_note text, p_card uuid) returns void
language plpgsql security definer set search_path to 'public' as $$
declare t maint_tasks;
begin
  select * into t from maint_tasks where id = p_task for update;
  if t.id is null then return; end if;
  insert into maint_task_log(task_id, done_on, done_by, note, card_id) values (p_task, p_on, p_by, p_note, p_card);
  update maint_tasks set next_due = maint_step_date(p_on, every_n, every_unit) where id = p_task;
end $$;

-- A calendar job past its date opens a job card on its own — once, while that card is open.
create or replace function maint_roll() returns int
language plpgsql security definer set search_path to 'public' as $$
declare t maint_tasks; c maint_cards; n int := 0;
begin
  for t in select * from maint_tasks x where x.active and x.next_due < maint_today()
             and not exists(select 1 from maint_cards k where k.task_id = x.id and k.checked_at is null) loop
    insert into maint_cards(source, task_id, is_test, reported_by, location, equipment, problem)
    values ('calendar', t.id, t.name ~* '^zz' or t.equipment ~* '^zz', 'Maintenance calendar',
      coalesce(nullif(t.location,''),'Kitchen'), coalesce(nullif(t.equipment,''), t.name),
      t.name || ' was due ' || to_char(t.next_due, 'FMDD Mon YYYY') || ' (every ' || t.every_n || ' ' || t.every_unit || case when t.every_n > 1 then 's' else '' end || ')' ||
      case when t.by_who <> '' then '. Done by: ' || t.by_who else '' end || case when t.notes <> '' then '. ' || t.notes else '' end)
    returning * into c;
    perform maint_queue(c.id, 'new');
    n := n + 1;
  end loop;
  return n;
end $$;

create or replace function maint_tasks_list(p_emp text) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s staff;
begin
  s := learn_who(p_emp);
  return jsonb_build_object('today', maint_today(), 'tasks', coalesce((select jsonb_agg(jsonb_build_object(
      'id', t.id, 'name', t.name, 'kind', t.kind, 'location', t.location, 'equipment', t.equipment,
      'every_n', t.every_n, 'every_unit', t.every_unit, 'next_due', t.next_due, 'by_who', t.by_who, 'notes', t.notes,
      'last', (select jsonb_build_object('on', l.done_on, 'by', l.done_by) from maint_task_log l where l.task_id = t.id order by l.done_on desc, l.done_at desc limit 1),
      'card', (select jsonb_build_object('id', k.id, 'card_no', k.card_no, 'status', k.status) from maint_cards k where k.task_id = t.id and k.checked_at is null order by k.reported_at desc limit 1),
      'log', (select coalesce(jsonb_agg(jsonb_build_object('on', l.done_on) order by l.done_on), '[]'::jsonb) from maint_task_log l where l.task_id = t.id and l.done_on > maint_today() - 400))
    order by t.next_due, t.name) from maint_tasks t where t.active), '[]'::jsonb));
end $$;

create or replace function maint_task_save(p_emp text, p_args jsonb) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s staff; a jsonb := coalesce(p_args,'{}'::jsonb); v_id uuid;
begin
  s := learn_who(p_emp);
  if not (maint_has(s.id,'technician') or maint_has(s.id,'chef')) then raise exception 'not_allowed' using errcode = 'P0001'; end if;
  if length(trim(coalesce(a->>'name',''))) < 2 then raise exception 'no_name' using errcode = 'P0001'; end if;
  if coalesce(a->>'every_n','') !~ '^\d{1,3}$' or (a->>'every_n')::int < 1 then raise exception 'bad_every' using errcode = 'P0001'; end if;
  if coalesce(a->>'next_due','') !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'no_date' using errcode = 'P0001'; end if;
  if nullif(a->>'id','') is null then
    insert into maint_tasks(name, kind, location, equipment, every_n, every_unit, next_due, by_who, notes, created_by)
    values (left(trim(a->>'name'),120), coalesce(nullif(a->>'kind',''),'other'), left(trim(coalesce(a->>'location','')),120), left(trim(coalesce(a->>'equipment','')),120),
      (a->>'every_n')::int, a->>'every_unit', (a->>'next_due')::date, left(trim(coalesce(a->>'by_who','')),120), left(trim(coalesce(a->>'notes','')),1000), s.name)
    returning id into v_id;
  else
    update maint_tasks set name = left(trim(a->>'name'),120), kind = coalesce(nullif(a->>'kind',''),'other'),
      location = left(trim(coalesce(a->>'location','')),120), equipment = left(trim(coalesce(a->>'equipment','')),120),
      every_n = (a->>'every_n')::int, every_unit = a->>'every_unit', next_due = (a->>'next_due')::date,
      by_who = left(trim(coalesce(a->>'by_who','')),120), notes = left(trim(coalesce(a->>'notes','')),1000)
    where id = (a->>'id')::uuid and active returning id into v_id;
    if v_id is null then raise exception 'no_task' using errcode = 'P0001'; end if;
  end if;
  perform maint_roll();
  return jsonb_build_object('id', v_id);
end $$;

create or replace function maint_task_done(p_emp text, p_id uuid, p_note text) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s staff; k maint_cards;
begin
  s := learn_who(p_emp);
  if not (maint_has(s.id,'technician') or maint_has(s.id,'chef')) then raise exception 'not_allowed' using errcode = 'P0001'; end if;
  select * into k from maint_cards where task_id = p_id and checked_at is null limit 1;
  if k.id is not null then raise exception 'has_card' using errcode = 'P0001'; end if;
  perform maint_task_did(p_id, maint_today(), s.name, nullif(trim(coalesce(p_note,'')),''), null);
  return jsonb_build_object('next_due', (select next_due from maint_tasks where id = p_id));
end $$;

create or replace function maint_task_remove(p_emp text, p_id uuid) returns void
language plpgsql security definer set search_path to 'public' as $$
declare s staff;
begin
  s := learn_who(p_emp);
  if not (maint_has(s.id,'technician') or maint_has(s.id,'chef')) then raise exception 'not_allowed' using errcode = 'P0001'; end if;
  update maint_tasks set active = false where id = p_id;
end $$;

-- ── grants ────────────────────────────────────────────────────────────────
revoke all on function maint_has(uuid,text), maint_kick(bigint), maint_queue(uuid,text), maint_card_row(maint_cards),
  maint_task_did(uuid,date,text,text,uuid), maint_roll() from public, anon, authenticated;
grant execute on function maint_me(text), maint_places(text), maint_list(text), maint_get(text,uuid), maint_read(text,uuid),
  maint_report(text,text,text,text,jsonb), maint_step(text,uuid,text,jsonb), maint_summary(),
  maint_tasks_list(text), maint_task_save(text,jsonb), maint_task_done(text,uuid,text), maint_task_remove(text,uuid) to anon, authenticated;

-- ── photos and videos ─────────────────────────────────────────────────────
-- Public bucket (a card's photos open by their long random address), 50 MB a file (the
-- project's own ceiling), images and video only. anon may ADD a file and nothing else: no
-- listing, no overwrite, no delete.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('maint-media', 'maint-media', true, 52428800, array['image/*','video/*'])
on conflict (id) do update set public = true, file_size_limit = 52428800, allowed_mime_types = array['image/*','video/*'];
drop policy if exists maint_media_add on storage.objects;
create policy maint_media_add on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'maint-media' and name ~ '^c/[0-9a-f-]{36}/[A-Za-z0-9._-]+$');

-- ── people (25 Sep 2026, Francesco) ───────────────────────────────────────
insert into maint_people(staff_id, role, email) values
  ('f23e9055-959f-4448-b9b5-00f68cbaec14', 'technician', 'afalcone@robertos.ae'),   -- Andrea Falcone, for testing
  ('d8c85cf5-d79d-4a2d-9b26-a66acee26911', 'chef',       'dvalla@robertos.ae'),     -- Danilo Valla
  ('ccf7e876-3288-44b7-8b58-8dcd72b22e01', 'chef',       'astellacci@robertos.ae')  -- Antonio Stellacci
on conflict (staff_id, role) do update set email = excluded.email, active = true;

-- ── timers ────────────────────────────────────────────────────────────────
-- Hourly: overdue calendar jobs open their cards. Every 10 minutes: any mail still queued after
-- 3 minutes, or failed fewer than 3 times, is handed to maint-notify again.
create or replace function maint_retry() returns int
language plpgsql security definer set search_path to 'public' as $$
declare r record; n int := 0;
begin
  update maint_mail set status = 'failed', error = coalesce(error,'') || ' (stuck sending)' where status = 'sending' and created_at < now() - interval '30 minutes' and sent_at is null;
  for r in select id from maint_mail where (status = 'queued' and created_at < now() - interval '3 minutes') or (status = 'failed' and tries < 3) loop
    perform maint_kick(r.id); n := n + 1;
  end loop;
  return n;
end $$;
revoke all on function maint_retry() from public, anon, authenticated;

select cron.unschedule(jobid) from cron.job where jobname in ('maint-roll-hourly','maint-mail-retry');
select cron.schedule('maint-roll-hourly', '5 * * * *', 'select maint_roll()');
select cron.schedule('maint-mail-retry', '*/10 * * * *', 'select maint_retry()');
